export const MAV_MODE_ENUM = {
    0: 'PREFLIGHT',
    64: 'MANUAL_DISARMED',
    66: 'TEST_DISARMED',
    80: 'STABILIZE_DISARMED',
    88: 'GUIDED_DISARMED',
    92: 'AUTO_DISARMED',
    192: 'MANUAL_ARMED',
    194: 'TEST_ARMED',
    208: 'STABILIZE_ARMED',
    216: 'GUIDED_ARMED',
    220: 'AUTO_ARMED',
};