"""Provider-neutral Simurgh Operator runtime primitives.

This package intentionally contains no model-provider SDK imports and no direct
drone API client. It is the policy, registry, approval, audit, session, and
context layer that future MCP or assistant adapters must pass through.
"""

from .approvals import InMemoryApprovalBroker
from .assistant import (
    ASSISTANT_CONFIG_ENV,
    ASSISTANT_HISTORY_FILE_ENV,
    ASSISTANT_HISTORY_MAX_AGE_DAYS_ENV,
    ASSISTANT_HISTORY_MAX_RECORDS_ENV,
    DEFAULT_ASSISTANT_CONFIG_PATH,
    DEFAULT_ASSISTANT_HISTORY_MAX_AGE_DAYS,
    DEFAULT_ASSISTANT_HISTORY_MAX_RECORDS,
    DEFAULT_ASSISTANT_HISTORY_PATH,
    DEFAULT_OPENAI_BASE_URL,
    DEFAULT_OPENAI_MODEL,
    OPENAI_API_KEY_FILE_ENV,
    OPENAI_ASSISTANT_PROVIDER,
    OPENAI_MODEL_ENV,
    SUPPORTED_ASSISTANT_PROVIDER,
    SUPPORTED_ASSISTANT_PROVIDERS,
    AssistantConfig,
    AssistantContextAssembler,
    AssistantContextDocument,
    AssistantHistoryStore,
    OpenAIProviderConfig,
    OpenAIResponsesAssistantAdapter,
    AssistantResponseTemplate,
    AssistantTurnHistoryRecord,
    AssistantTurnRecord,
    AssistantTurnResult,
    MockAssistantAdapter,
    blocked_intent_matches,
    create_assistant_turn,
    create_mock_assistant_turn,
    load_default_assistant_config,
    sensitive_input_matches,
    validate_openai_api_key_file,
)
from .audit import InMemoryAuditSink, JsonlAuditSink
from .context import AgentContextIndex, load_default_context_index
from .evals import (
    DEFAULT_ASSISTANT_EVAL_SUITE_PATH,
    AssistantEvalExpectation,
    AssistantEvalResult,
    AssistantEvalRunReport,
    AssistantEvalScenario,
    AssistantEvalSuite,
    ProviderResponseFixture,
    load_default_assistant_eval_suite,
    run_assistant_eval_scenario,
    run_assistant_eval_suite,
)
from .provider_smoke import (
    DEFAULT_PROVIDER_SMOKE_SUITE_PATH,
    ProviderSmokeExpectation,
    ProviderSmokeResult,
    ProviderSmokeRunReport,
    ProviderSmokeScenario,
    ProviderSmokeSuite,
    load_default_provider_smoke_suite,
    run_provider_smoke_scenario,
    run_provider_smoke_suite,
)
from .mcp_metadata import (
    MCP_ALLOWED_ORIGINS_ENV,
    MCP_AUTHORIZATION_SERVERS_ENV,
    MCP_ENDPOINT_PATH,
    MCP_PROTOCOL_VERSION,
    MCP_REQUIRE_AUTH_ENV,
    MCP_REQUIRED_SCOPES_ENV,
    MCP_RESOURCE_PREFIX,
    MCP_RESOURCE_URL_ENV,
    SimurghMcpResourceProvider,
    is_mcp_origin_allowed,
    is_mcp_auth_required,
    mcp_bearer_challenge,
    mcp_protected_resource_metadata,
    mcp_required_scopes,
    mcp_server_info,
    mcp_server_instructions,
    require_mcp_runtime_enabled,
)
from .models import (
    AgentRuntimeError,
    AgentSession,
    ApprovalRecord,
    ApprovalStatus,
    AuditEvent,
    ContextResource,
    PolicyDecision,
    PolicyDecisionStatus,
    ToolDefinition,
    ToolExposure,
    ToolRiskClass,
)
from .policy import AgentPolicy, load_default_policy
from .sessions import AgentSessionStore, sanitize_session_metadata
from .tool_registry import ToolRegistry, load_default_tool_registry

__all__ = [
    "AgentContextIndex",
    "AgentPolicy",
    "AgentRuntimeError",
    "AgentSession",
    "AgentSessionStore",
    "ASSISTANT_CONFIG_ENV",
    "ASSISTANT_HISTORY_FILE_ENV",
    "ASSISTANT_HISTORY_MAX_AGE_DAYS_ENV",
    "ASSISTANT_HISTORY_MAX_RECORDS_ENV",
    "AssistantConfig",
    "AssistantContextAssembler",
    "AssistantContextDocument",
    "AssistantEvalExpectation",
    "AssistantEvalResult",
    "AssistantEvalRunReport",
    "AssistantEvalScenario",
    "AssistantEvalSuite",
    "AssistantHistoryStore",
    "AssistantResponseTemplate",
    "AssistantTurnHistoryRecord",
    "AssistantTurnRecord",
    "AssistantTurnResult",
    "ApprovalRecord",
    "ApprovalStatus",
    "AuditEvent",
    "ContextResource",
    "DEFAULT_ASSISTANT_CONFIG_PATH",
    "DEFAULT_ASSISTANT_EVAL_SUITE_PATH",
    "DEFAULT_ASSISTANT_HISTORY_MAX_AGE_DAYS",
    "DEFAULT_ASSISTANT_HISTORY_MAX_RECORDS",
    "DEFAULT_ASSISTANT_HISTORY_PATH",
    "DEFAULT_OPENAI_BASE_URL",
    "DEFAULT_OPENAI_MODEL",
    "DEFAULT_PROVIDER_SMOKE_SUITE_PATH",
    "InMemoryApprovalBroker",
    "InMemoryAuditSink",
    "JsonlAuditSink",
    "MCP_ALLOWED_ORIGINS_ENV",
    "MCP_AUTHORIZATION_SERVERS_ENV",
    "MCP_ENDPOINT_PATH",
    "MCP_PROTOCOL_VERSION",
    "MCP_REQUIRE_AUTH_ENV",
    "MCP_REQUIRED_SCOPES_ENV",
    "MCP_RESOURCE_PREFIX",
    "MCP_RESOURCE_URL_ENV",
    "MockAssistantAdapter",
    "OPENAI_API_KEY_FILE_ENV",
    "OPENAI_ASSISTANT_PROVIDER",
    "OPENAI_MODEL_ENV",
    "OpenAIProviderConfig",
    "OpenAIResponsesAssistantAdapter",
    "PolicyDecision",
    "PolicyDecisionStatus",
    "ProviderSmokeExpectation",
    "ProviderSmokeResult",
    "ProviderSmokeRunReport",
    "ProviderSmokeScenario",
    "ProviderSmokeSuite",
    "ProviderResponseFixture",
    "SimurghMcpResourceProvider",
    "SUPPORTED_ASSISTANT_PROVIDER",
    "SUPPORTED_ASSISTANT_PROVIDERS",
    "ToolDefinition",
    "ToolExposure",
    "ToolRegistry",
    "ToolRiskClass",
    "is_mcp_auth_required",
    "is_mcp_origin_allowed",
    "blocked_intent_matches",
    "create_assistant_turn",
    "create_mock_assistant_turn",
    "load_default_assistant_config",
    "load_default_assistant_eval_suite",
    "load_default_provider_smoke_suite",
    "load_default_context_index",
    "load_default_policy",
    "load_default_tool_registry",
    "mcp_bearer_challenge",
    "mcp_protected_resource_metadata",
    "mcp_required_scopes",
    "mcp_server_info",
    "mcp_server_instructions",
    "require_mcp_runtime_enabled",
    "run_assistant_eval_scenario",
    "run_assistant_eval_suite",
    "run_provider_smoke_scenario",
    "run_provider_smoke_suite",
    "sanitize_session_metadata",
    "sensitive_input_matches",
    "validate_openai_api_key_file",
]
