#!/bin/bash
# =============================================================================
# MDS GCS Initialization Library: Environment Configuration
# =============================================================================
# Version: 1.0.0
# Description: Configure .env files for GCS operation
# Author: MDS Team
# =============================================================================

# Prevent double-sourcing
[[ -n "${_MDS_GCS_ENV_CONFIG_LOADED:-}" ]] && return 0
_MDS_GCS_ENV_CONFIG_LOADED=1

# =============================================================================
# CONSTANTS
# =============================================================================

readonly GCS_DASHBOARD_ENV_EXAMPLE=".env.example"
readonly GCS_DASHBOARD_ENV=".env"

get_existing_gcs_env_value() {
    local key="$1"
    local env_file="${2:-$GCS_CONFIG_FILE}"

    if [[ ! -f "$env_file" ]]; then
        return 1
    fi

    awk -F= -v target="$key" '$1 == target {print substr($0, index($0, "=") + 1); exit}' "$env_file"
}

# =============================================================================
# DASHBOARD .env CONFIGURATION
# =============================================================================

# Get dashboard .env path
get_dashboard_env_path() {
    local dashboard_path
    dashboard_path=$(get_dashboard_path)
    echo "${dashboard_path}/${GCS_DASHBOARD_ENV}"
}

# Get dashboard .env.example path
get_dashboard_env_example_path() {
    local dashboard_path
    dashboard_path=$(get_dashboard_path)
    echo "${dashboard_path}/${GCS_DASHBOARD_ENV_EXAMPLE}"
}

# Configure dashboard .env
configure_dashboard_env() {
    local dashboard_path
    dashboard_path=$(get_dashboard_path)
    local env_file
    env_file=$(get_dashboard_env_path)
    local env_example
    env_example=$(get_dashboard_env_example_path)

    log_step "Configuring dashboard .env..."

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would configure: $env_file${NC}"
        return 0
    fi

    # Check if .env already exists
    if [[ -f "$env_file" ]]; then
        log_info ".env already exists"

        if [[ "${NON_INTERACTIVE:-false}" != "true" ]]; then
            if ! confirm "Reconfigure .env file?" "n"; then
                log_info "Keeping existing .env"
                return 0
            fi
            # Backup existing
            backup_file "$env_file"
        else
            log_info "Keeping existing .env (non-interactive mode)"
            return 0
        fi
    fi

    # Copy from .env.example if it exists
    if [[ -f "$env_example" ]]; then
        cp "$env_example" "$env_file"
        log_info "Copied from .env.example"
    else
        # Create minimal .env
        cat > "$env_file" << 'EOF'
# MDS Dashboard Configuration
# Generated by mds_gcs_init.sh

# Mapbox Token (optional - for map features)
# Get a free token at https://www.mapbox.com/
REACT_APP_MAPBOX_ACCESS_TOKEN=

# Note: REACT_APP_SERVER_URL is deprecated
# The dashboard now auto-detects the backend URL
EOF
        log_info "Created new .env file"
    fi

    # Prompt for Mapbox token
    if [[ "${NON_INTERACTIVE:-false}" != "true" ]]; then
        echo ""
        echo -e "  ${WHITE}Mapbox Token Configuration${NC}"
        echo -e "  ${DIM}───────────────────────────────────────────────────────────────${NC}"
        echo -e "  Mapbox provides map tiles for the dashboard."
        echo -e "  Get a free token at: ${CYAN}https://www.mapbox.com/${NC}"
        echo ""

        local mapbox_token=""
        prompt_input "Mapbox token (leave empty to skip)" "" mapbox_token

        if [[ -n "$mapbox_token" ]]; then
            # Update the token in .env (escape special characters for sed)
            local escaped_token
            escaped_token=$(printf '%s\n' "$mapbox_token" | sed -e 's/[\/&|]/\\&/g')
            sed -i "s|^REACT_APP_MAPBOX_ACCESS_TOKEN=.*|REACT_APP_MAPBOX_ACCESS_TOKEN=${escaped_token}|" "$env_file"
            log_success "Mapbox token configured"
        else
            log_info "Mapbox token skipped (can be added later)"
        fi
    fi

    log_success "Dashboard .env configured"
    return 0
}

# =============================================================================
# SYSTEM .env CONFIGURATION
# =============================================================================

# Configure GCS system environment file
configure_gcs_env() {
    log_step "Configuring system GCS environment..."

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would configure: ${GCS_CONFIG_FILE}${NC}"
        return 0
    fi

    local install_dir="${GCS_INSTALL_DIR:-$(pwd)}"
    local repo_url
    repo_url=$(gcs_state_get_value "repo_url" "$GCS_DEFAULT_REPO_SSH")
    local repo_branch
    repo_branch=$(gcs_state_get_value "repo_branch" "$GCS_DEFAULT_BRANCH")
    local gcs_api_port="${MDS_DEFAULT_GCS_API_PORT:-5030}"
    local dashboard_port="${MDS_DEFAULT_DASHBOARD_PORT:-3030}"
    local git_auth_token_file="${MDS_GIT_AUTH_TOKEN_FILE:-}"
    local git_ssh_key_file="${MDS_GIT_SSH_KEY_FILE:-}"
    local access_method
    access_method=$(gcs_state_get_value "access_method" "ssh")
    local git_auto_push="true"
    if [[ "$access_method" == "https" ]]; then
        git_auto_push="false"
    fi

    # Create /etc/mds directory if needed
    mkdir -p "$(dirname "$GCS_CONFIG_FILE")"

    local existing_repo_url=""
    local existing_repo_branch=""
    local existing_git_auto_push=""
    local existing_git_auth_token_file=""
    local existing_git_ssh_key_file=""
    local existing_install_dir=""
    local existing_mode=""
    local config_matches="false"

    if [[ -f "$GCS_CONFIG_FILE" ]]; then
        existing_repo_url=$(get_existing_gcs_env_value "MDS_REPO_URL" "$GCS_CONFIG_FILE" || true)
        existing_repo_branch=$(get_existing_gcs_env_value "MDS_BRANCH" "$GCS_CONFIG_FILE" || true)
        existing_git_auto_push=$(get_existing_gcs_env_value "MDS_GIT_AUTO_PUSH" "$GCS_CONFIG_FILE" || true)
        existing_git_auth_token_file=$(get_existing_gcs_env_value "MDS_GIT_AUTH_TOKEN_FILE" "$GCS_CONFIG_FILE" || true)
        existing_git_ssh_key_file=$(get_existing_gcs_env_value "MDS_GIT_SSH_KEY_FILE" "$GCS_CONFIG_FILE" || true)
        existing_install_dir=$(get_existing_gcs_env_value "MDS_INSTALL_DIR" "$GCS_CONFIG_FILE" || true)
        existing_mode=$(get_existing_gcs_env_value "MDS_MODE" "$GCS_CONFIG_FILE" || true)

        if [[ "$existing_repo_url" == "$repo_url" ]] && \
           [[ "$existing_repo_branch" == "$repo_branch" ]] && \
           [[ "$existing_git_auto_push" == "$git_auto_push" ]] && \
           [[ "$existing_git_auth_token_file" == "$git_auth_token_file" ]] && \
           [[ "$existing_git_ssh_key_file" == "$git_ssh_key_file" ]] && \
           [[ "$existing_install_dir" == "$install_dir" ]] && \
           [[ "$existing_mode" == "real" ]]; then
            config_matches="true"
        fi
    fi

    # Check if file exists
    if [[ -f "$GCS_CONFIG_FILE" ]]; then
        if [[ "$config_matches" == "true" ]]; then
            log_info "GCS configuration already matches requested repo and branch"
            return 0
        fi

        if [[ "${NON_INTERACTIVE:-false}" != "true" ]]; then
            if ! confirm "Reconfigure ${GCS_CONFIG_FILE}?" "n"; then
                log_info "Keeping existing GCS configuration"
                return 0
            fi
            backup_file "$GCS_CONFIG_FILE"
        else
            backup_file "$GCS_CONFIG_FILE"
            log_info "Updating existing GCS configuration to match requested repo and branch"
        fi
    fi

    # Create GCS config file
    cat > "$GCS_CONFIG_FILE" << EOF
# MDS GCS Configuration
# Generated by mds_gcs_init.sh on $(date -Iseconds)

# GCS Server Settings
GCS_PORT=${gcs_api_port}
MDS_GCS_API_PORT=${gcs_api_port}
GCS_BACKEND=fastapi
MDS_MODE=real

# Repository Settings
MDS_REPO_URL=${repo_url}
MDS_BRANCH=${repo_branch}
MDS_GIT_AUTO_PUSH=${git_auto_push}
MDS_GIT_AUTH_TOKEN_FILE=${git_auth_token_file}
MDS_GIT_SSH_KEY_FILE=${git_ssh_key_file}
MDS_INSTALL_DIR=${install_dir}

# Dashboard Settings
DASHBOARD_PORT=${dashboard_port}
MDS_DASHBOARD_PORT=${dashboard_port}

# Virtual Environment
VENV_PATH=${install_dir}/venv
EOF

    chmod 644 "$GCS_CONFIG_FILE"
    log_success "GCS system configuration created: ${GCS_CONFIG_FILE}"
    if [[ "$git_auto_push" == "false" ]]; then
        log_info "Set MDS_GIT_AUTO_PUSH=false because this GCS is configured with an HTTPS/read-only repository."
    fi

    return 0
}

# =============================================================================
# DEPRECATED ITEMS HANDLING
# =============================================================================

# Handle deprecated configuration items
handle_deprecated_items() {
    local env_file
    env_file=$(get_dashboard_env_path)

    log_step "Checking for deprecated configuration..."

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would check for deprecated items${NC}"
        return 0
    fi

    if [[ ! -f "$env_file" ]]; then
        return 0
    fi

    local deprecated_found=false

    # Check for deprecated REACT_APP_SERVER_URL
    if grep -q "^REACT_APP_SERVER_URL=" "$env_file" 2>/dev/null; then
        local server_url
        server_url=$(grep "^REACT_APP_SERVER_URL=" "$env_file" | cut -d'=' -f2-)

        if [[ -n "$server_url" ]] && [[ "$server_url" != "http://localhost:5030" ]]; then
            deprecated_found=true
            log_warn "REACT_APP_SERVER_URL is deprecated (found: $server_url)"
            echo -e "  ${DIM}The dashboard now auto-detects the backend URL.${NC}"
            echo -e "  ${DIM}This setting will be ignored unless you're using a custom backend.${NC}"
        fi
    fi

    if [[ "$deprecated_found" == "false" ]]; then
        log_info "No deprecated items found"
    fi

    return 0
}

# =============================================================================
# MAIN PHASE RUNNER
# =============================================================================

run_env_config_phase() {
    print_phase_header "8" "Environment Configuration" "9"

    # Check skip flag
    if [[ "${SKIP_ENV_CONFIG:-false}" == "true" ]]; then
        log_info "Skipping environment configuration (--skip-env-config)"
        return 0
    fi

    print_section "Dashboard Configuration"
    configure_dashboard_env || return 1

    print_section "System Configuration"
    configure_gcs_env || return 1

    print_section "Deprecated Items"
    handle_deprecated_items || return 1

    echo ""
    log_success "Environment configuration phase completed"
    return 0
}
