#!/bin/bash
# =============================================================================
# MDS Initialization Library: Network Configuration
# =============================================================================
# Version: 4.4.0
# Description: NTP time sync, static IP, and Netbird VPN configuration
# Author: MDS Team
# =============================================================================

# Prevent double-sourcing
[[ -n "${_MDS_NETWORK_LOADED:-}" ]] && return 0
_MDS_NETWORK_LOADED=1

# =============================================================================
# CONSTANTS
# =============================================================================

readonly TIMESYNCD_CONF="/etc/systemd/timesyncd.conf"
readonly DHCPCD_CONF="/etc/dhcpcd.conf"

# NTP servers in priority order
readonly NTP_SERVERS=(
    "0.pool.ntp.org"
    "1.pool.ntp.org"
    "2.pool.ntp.org"
    "3.pool.ntp.org"
)

readonly FALLBACK_NTP="ntp.ubuntu.com"

# =============================================================================
# NTP CONFIGURATION
# =============================================================================

# Configure NTP servers
configure_ntp() {
    log_step "Configuring NTP time synchronization..."

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would configure NTP servers${NC}"
        return 0
    fi

    # Backup existing config
    if [[ -f "${TIMESYNCD_CONF}" ]]; then
        backup_file "${TIMESYNCD_CONF}"
    fi

    # Check if [Time] section exists
    if grep -q "^\[Time\]" "${TIMESYNCD_CONF}" 2>/dev/null; then
        # Update existing NTP line
        sed -i "s/^#*NTP=.*/NTP=${NTP_SERVERS[*]}/" "${TIMESYNCD_CONF}"
        sed -i "s/^#*FallbackNTP=.*/FallbackNTP=${FALLBACK_NTP}/" "${TIMESYNCD_CONF}"
    else
        # Create new config
        cat > "${TIMESYNCD_CONF}" << EOF
# MDS NTP Configuration
# Generated by mds_node_init.sh

[Time]
NTP=${NTP_SERVERS[*]}
FallbackNTP=${FALLBACK_NTP}
EOF
    fi

    chmod 644 "${TIMESYNCD_CONF}"
    log_success "NTP servers configured"
    return 0
}

# Enable NTP synchronization
enable_ntp_sync() {
    log_step "Enabling NTP synchronization..."

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would enable NTP sync${NC}"
        return 0
    fi

    # Enable time sync
    timedatectl set-ntp true 2>/dev/null || {
        log_warn "timedatectl set-ntp failed, trying alternative method"
        systemctl enable systemd-timesyncd 2>/dev/null || true
        systemctl start systemd-timesyncd 2>/dev/null || true
    }

    log_success "NTP synchronization enabled"
    return 0
}

# Verify time synchronization
verify_time_sync() {
    log_step "Verifying time synchronization..."

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would verify NTP sync${NC}"
        return 0
    fi

    # Check timedatectl status
    local sync_status
    sync_status=$(timedatectl show --property=NTPSynchronized --value 2>/dev/null || echo "no")

    if [[ "$sync_status" == "yes" ]]; then
        log_success "System time is synchronized"
        return 0
    fi

    # Not yet synced - may take a moment
    log_info "Time sync in progress (may take a few seconds)"

    # Wait briefly and check again
    sleep 3
    sync_status=$(timedatectl show --property=NTPSynchronized --value 2>/dev/null || echo "no")

    if [[ "$sync_status" == "yes" ]]; then
        log_success "System time is synchronized"
        return 0
    fi

    log_warn "Time sync not confirmed yet (will sync automatically)"
    return 0
}

# Display time info
display_time_info() {
    echo ""
    echo -e "  ${BOLD}Time Configuration:${NC}"
    echo -e "  ${DIM}$(printf '%.0s─' {1..50})${NC}"

    local current_time timezone ntp_status
    current_time=$(date '+%Y-%m-%d %H:%M:%S %Z')
    timezone=$(timedatectl show --property=Timezone --value 2>/dev/null || echo "Unknown")
    ntp_status=$(timedatectl show --property=NTPSynchronized --value 2>/dev/null || echo "Unknown")

    echo "  Current time: $current_time"
    echo "  Timezone:     $timezone"
    echo "  NTP synced:   $ntp_status"
    echo ""
}

# =============================================================================
# STATIC IP CONFIGURATION
# =============================================================================

# Detect primary network interface
detect_network_interface() {
    # Try to find the default route interface
    local iface
    iface=$(ip route show default 2>/dev/null | awk '/default/ {print $5}' | head -1)

    if [[ -n "$iface" ]]; then
        echo "$iface"
        return 0
    fi

    # Fallback: look for eth0 or wlan0
    for candidate in eth0 wlan0 enp0s3; do
        if ip link show "$candidate" &>/dev/null; then
            echo "$candidate"
            return 0
        fi
    done

    echo ""
    return 1
}

# Get current IP information
get_current_ip_info() {
    local iface="$1"

    if [[ -z "$iface" ]]; then
        iface=$(detect_network_interface)
    fi

    if [[ -z "$iface" ]]; then
        return 1
    fi

    local ip gateway
    ip=$(ip -4 addr show "$iface" 2>/dev/null | grep -oP 'inet \K[\d.]+/\d+' | head -1)
    gateway=$(ip route show default 2>/dev/null | awk '/default/ {print $3}' | head -1)

    echo "interface=$iface"
    echo "ip=$ip"
    echo "gateway=$gateway"
}

# Display current network information
display_network_info() {
    local iface
    iface=$(detect_network_interface)

    echo ""
    echo -e "  ${BOLD}Current Network Configuration:${NC}"
    echo -e "  ${DIM}$(printf '%.0s─' {1..50})${NC}"

    if [[ -z "$iface" ]]; then
        echo "  No active network interface detected"
        return 1
    fi

    local ip gateway
    ip=$(ip -4 addr show "$iface" 2>/dev/null | grep -oP 'inet \K[\d.]+/\d+' | head -1)
    gateway=$(ip route show default 2>/dev/null | awk '/default/ {print $3}' | head -1)

    echo "  Interface: $iface"
    echo "  IP:        ${ip:-not assigned}"
    echo "  Gateway:   ${gateway:-not set}"
    echo ""
}

# Display comprehensive network configuration box
display_network_config_box() {
    local iface
    iface=$(detect_network_interface)

    local ip gateway source
    ip=$(ip -4 addr show "$iface" 2>/dev/null | grep -oP 'inet \K[\d.]+/\d+' | head -1)
    gateway=$(ip route show default 2>/dev/null | awk '/default/ {print $3}' | head -1)

    # Detect source type
    if [[ "$iface" == wlan* ]]; then
        source="WiFi"
    elif [[ "$iface" == eth* ]] || [[ "$iface" == enp* ]]; then
        source="Ethernet"
    elif [[ "$iface" == usb* ]]; then
        source="USB Tethering"
    else
        source="Unknown"
    fi

    # Detect if DHCP or static
    local dhcp_status="DHCP"
    if [[ -f /etc/dhcpcd.conf ]] && grep -q "interface ${iface}" /etc/dhcpcd.conf 2>/dev/null; then
        if grep -A5 "interface ${iface}" /etc/dhcpcd.conf 2>/dev/null | grep -q "static ip_address"; then
            dhcp_status="Static"
        fi
    fi

    echo ""
    echo -e "${CYAN}┌────────────────────────────────────────────────────────────────────────────┐${NC}"
    echo -e "${CYAN}│${NC}  ${WHITE}Network Configuration${NC}                                                     ${CYAN}│${NC}"
    echo -e "${CYAN}├────────────────────────────────────────────────────────────────────────────┤${NC}"
    echo -e "${CYAN}│${NC}                                                                            ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}  ${BOLD}Current Network:${NC}                                                         ${CYAN}│${NC}"
    printf "${CYAN}│${NC}    Interface:  %-58s ${CYAN}│${NC}\n" "${iface:-none}"
    printf "${CYAN}│${NC}    IP Address: %-58s ${CYAN}│${NC}\n" "${ip:-not assigned} (${dhcp_status})"
    printf "${CYAN}│${NC}    Gateway:    %-58s ${CYAN}│${NC}\n" "${gateway:-not set}"
    printf "${CYAN}│${NC}    Source:     %-58s ${CYAN}│${NC}\n" "$source"
    echo -e "${CYAN}│${NC}                                                                            ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}  ${BOLD}Options:${NC}                                                                 ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}                                                                            ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}    ${GREEN}[1]${NC} Keep DHCP (current) + Use NetBird VPN for drone/GCS communication  ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}        ${DIM}- Recommended for most setups${NC}                                       ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}        ${DIM}- Works across any network${NC}                                          ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}                                                                            ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}    ${GREEN}[2]${NC} Set static IP on current network                                   ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}        ${YELLOW}Warning: May disconnect SSH if IP changes${NC}                          ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}        ${YELLOW}Only use if you understand network configuration${NC}                   ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}                                                                            ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}    ${GREEN}[3]${NC} Skip network configuration                                         ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}                                                                            ${CYAN}│${NC}"
    echo -e "${CYAN}└────────────────────────────────────────────────────────────────────────────┘${NC}"
    echo ""
}

# Configure static IP (using dhcpcd)
configure_static_ip_dhcpcd() {
    local iface="$1"
    local static_ip="$2"
    local gateway="$3"

    log_step "Configuring static IP via dhcpcd..."

    if [[ ! -f "${DHCPCD_CONF}" ]]; then
        log_warn "dhcpcd.conf not found - using NetworkManager instead"
        return 1
    fi

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would configure: ${DHCPCD_CONF}${NC}"
        echo -e "  ${DIM}  Interface: $iface${NC}"
        echo -e "  ${DIM}  IP: $static_ip${NC}"
        echo -e "  ${DIM}  Gateway: $gateway${NC}"
        return 0
    fi

    # Backup config
    backup_file "${DHCPCD_CONF}"

    # Check if interface config already exists
    if grep -q "interface ${iface}" "${DHCPCD_CONF}" 2>/dev/null; then
        log_warn "Static IP already configured for ${iface} in dhcpcd.conf"
        log_info "Please manually edit ${DHCPCD_CONF} to update"
        return 0
    fi

    # Append static IP configuration
    cat >> "${DHCPCD_CONF}" << EOF

# MDS Static IP Configuration
# Generated by mds_node_init.sh on $(date '+%Y-%m-%d %H:%M:%S')
interface ${iface}
static ip_address=${static_ip}
static routers=${gateway}
static domain_name_servers=${gateway} 8.8.8.8 8.8.4.4
EOF

    log_success "Static IP configured in ${DHCPCD_CONF}"
    log_warn "Reboot required to apply static IP changes"
    return 0
}

# Configure static IP (using NetworkManager)
configure_static_ip_nm() {
    local iface="$1"
    local static_ip="$2"
    local gateway="$3"

    log_step "Configuring static IP via NetworkManager..."

    if ! command_exists nmcli; then
        log_warn "NetworkManager not available"
        return 1
    fi

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would configure static IP via nmcli${NC}"
        return 0
    fi

    # Get connection name
    local conn_name
    conn_name=$(nmcli -t -f NAME,DEVICE connection show --active | grep ":${iface}$" | cut -d: -f1)

    if [[ -z "$conn_name" ]]; then
        log_warn "No active connection found for ${iface}"
        return 1
    fi

    # Configure static IP
    nmcli connection modify "$conn_name" ipv4.method manual ipv4.addresses "$static_ip" ipv4.gateway "$gateway" ipv4.dns "8.8.8.8 8.8.4.4"

    log_success "Static IP configured for connection: $conn_name"
    log_warn "Run 'nmcli connection down/up \"$conn_name\"' to apply changes"
    return 0
}

# =============================================================================
# NETBIRD VPN
# =============================================================================

# Check if Netbird is installed
check_netbird_installed() {
    command_exists netbird
}

# Install Netbird
install_netbird() {
    log_step "Installing Netbird VPN..."

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would install Netbird${NC}"
        return 0
    fi

    # Use official install script
    log_info "Downloading Netbird installer..."
    curl -fsSL https://pkgs.netbird.io/install.sh | sh || {
        log_error "Failed to install Netbird"
        return 1
    }

    log_success "Netbird installed"
    return 0
}

# Configure Netbird
configure_netbird() {
    local setup_key="$1"
    local management_url="${2:-}"

    log_step "Configuring Netbird..."

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would configure Netbird with setup key${NC}"
        return 0
    fi

    local cmd="netbird up --setup-key ${setup_key}"

    if [[ -n "$management_url" ]]; then
        cmd="$cmd --management-url ${management_url}"
    fi

    # Run netbird up
    if eval "$cmd"; then
        log_success "Netbird configured and connected"

        # Show assigned IP
        local nb_ip
        nb_ip=$(netbird status 2>/dev/null | grep -oP 'IP: \K[\d.]+' | head -1)
        if [[ -n "$nb_ip" ]]; then
            log_info "Netbird IP: $nb_ip"
            state_set_value "netbird_ip" "$nb_ip"
        fi

        return 0
    fi

    log_error "Failed to configure Netbird"
    return 1
}

# Get Netbird status
get_netbird_status() {
    if ! check_netbird_installed; then
        echo "not_installed"
        return
    fi

    local status
    status=$(netbird status 2>/dev/null | grep -i "status:" | head -1 | awk '{print $2}')
    echo "${status:-unknown}"
}

# Display Netbird info
display_netbird_info() {
    echo ""
    echo -e "  ${BOLD}Netbird VPN Status:${NC}"
    echo -e "  ${DIM}$(printf '%.0s─' {1..50})${NC}"

    if ! check_netbird_installed; then
        echo "  Status: not installed"
        return
    fi

    netbird status 2>/dev/null | while read -r line; do
        echo "  $line"
    done
    echo ""
}

# Display NetBird configuration selection box
display_netbird_config_box() {
    echo ""
    echo -e "${CYAN}┌────────────────────────────────────────────────────────────────────────────┐${NC}"
    echo -e "${CYAN}│${NC}  ${WHITE}NetBird VPN Configuration${NC}                                                ${CYAN}│${NC}"
    echo -e "${CYAN}├────────────────────────────────────────────────────────────────────────────┤${NC}"
    echo -e "${CYAN}│${NC}                                                                            ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}  NetBird provides secure VPN connectivity between drones and GCS.         ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}                                                                            ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}  ${BOLD}Which NetBird setup do you use?${NC}                                          ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}                                                                            ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}    ${GREEN}[1]${NC} Official NetBird Cloud (netbird.io)                                 ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}        ${DIM}- Easiest setup, managed infrastructure${NC}                             ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}        ${DIM}- Requires: Setup key from app.netbird.io${NC}                           ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}                                                                            ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}    ${GREEN}[2]${NC} Self-hosted NetBird Server                                         ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}        ${DIM}- Custom management URL required${NC}                                    ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}        ${DIM}- Requires: Management URL + Setup key${NC}                              ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}                                                                            ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}    ${GREEN}[3]${NC} Skip NetBird (configure manually later)                            ${CYAN}│${NC}"
    echo -e "${CYAN}│${NC}                                                                            ${CYAN}│${NC}"
    echo -e "${CYAN}└────────────────────────────────────────────────────────────────────────────┘${NC}"
    echo ""
}

# Prompt for NetBird configuration interactively
prompt_netbird_config() {
    # If key already provided via CLI, skip prompt
    if [[ -n "${NETBIRD_KEY:-}" ]]; then
        log_info "NetBird setup key provided via CLI"
        return 0
    fi

    display_netbird_config_box

    local choice=""
    prompt_input "Select option (1-3)" "3" choice

    case "$choice" in
        1)
            # Official NetBird Cloud
            log_info "Using official NetBird Cloud (netbird.io)"
            echo ""
            echo -e "  ${INFO} Get your setup key from: ${GREEN}https://app.netbird.io${NC}"
            echo ""
            prompt_input "Enter NetBird setup key" "" NETBIRD_KEY

            if [[ -z "${NETBIRD_KEY:-}" ]]; then
                log_warn "No setup key provided, skipping NetBird"
                return 1
            fi
            ;;
        2)
            # Self-hosted
            log_info "Using self-hosted NetBird server"
            echo ""
            prompt_input "Enter management URL (e.g., https://netbird.mycompany.com)" "" NETBIRD_URL
            prompt_input "Enter setup key" "" NETBIRD_KEY

            if [[ -z "${NETBIRD_KEY:-}" ]]; then
                log_warn "No setup key provided, skipping NetBird"
                return 1
            fi

            if [[ -z "${NETBIRD_URL:-}" ]]; then
                log_warn "No management URL provided, skipping NetBird"
                return 1
            fi
            ;;
        3|*)
            log_info "Skipping NetBird configuration"
            return 1
            ;;
    esac

    return 0
}

# =============================================================================
# MAIN NETWORK RUNNERS
# =============================================================================

# Run NTP phase
run_ntp_phase() {
    print_phase_header "10" "Time Synchronization"

    # Check skip flag
    if [[ "${SKIP_NTP:-false}" == "true" ]]; then
        log_info "Skipping NTP configuration (--skip-ntp)"
        return 0
    fi

    print_section "NTP Configuration"

    configure_ntp || return 1
    enable_ntp_sync || return 1

    print_section "Verification"

    verify_time_sync

    if [[ "${VERBOSE:-false}" == "true" ]]; then
        display_time_info
    fi

    log_success "Time synchronization configured"
    return 0
}

# Run Netbird phase
run_netbird_phase() {
    print_phase_header "11" "Netbird VPN"

    # Check skip flag
    if [[ "${SKIP_NETBIRD:-false}" == "true" ]]; then
        log_info "Skipping Netbird configuration (--skip-netbird)"
        return 0
    fi

    # Check if setup key provided via CLI
    if [[ -z "${NETBIRD_KEY:-}" ]]; then
        log_info "No Netbird setup key provided via CLI"

        if [[ "${NON_INTERACTIVE:-false}" != "true" ]]; then
            # Use the new interactive prompt
            if ! prompt_netbird_config; then
                log_info "Skipping Netbird configuration"
                return 0
            fi
        else
            log_info "Skipping Netbird (no key in non-interactive mode)"
            return 0
        fi
    fi

    if [[ -z "${NETBIRD_KEY:-}" ]]; then
        log_info "No setup key provided, skipping Netbird"
        return 0
    fi

    print_section "Installation"

    if ! check_netbird_installed; then
        install_netbird || return 1
    else
        log_success "Netbird already installed"
    fi

    print_section "Configuration"

    echo ""
    echo -e "  ${YELLOW}WARNING: Netbird connection may briefly interrupt SSH access.${NC}"
    echo ""

    if [[ "${NON_INTERACTIVE:-false}" != "true" ]]; then
        if ! confirm "Proceed with Netbird configuration?" "y"; then
            log_info "Netbird configuration skipped"
            return 0
        fi
    fi

    configure_netbird "${NETBIRD_KEY}" "${NETBIRD_URL:-}" || return 1

    if [[ "${VERBOSE:-false}" == "true" ]]; then
        display_netbird_info
    fi

    log_success "Netbird VPN configured"
    return 0
}

# Run Static IP phase
run_static_ip_phase() {
    print_phase_header "12" "Static IP Configuration"

    # Check if static IP was requested via CLI
    if [[ -z "${STATIC_IP:-}" ]]; then
        log_info "No static IP requested via CLI"

        if [[ "${NON_INTERACTIVE:-false}" != "true" ]]; then
            # Show comprehensive network config box
            display_network_config_box

            local choice=""
            prompt_input "Select option (1-3)" "1" choice

            case "$choice" in
                1)
                    # Keep DHCP + VPN recommendation
                    log_info "Keeping DHCP configuration (VPN recommended for communication)"
                    return 0
                    ;;
                2)
                    # Static IP - show warning and prompt
                    echo ""
                    echo -e "  ${YELLOW}┌─────────────────────────────────────────────────────────────┐${NC}"
                    echo -e "  ${YELLOW}│${NC}  ${RED}WARNING: SSH connection may be lost if IP changes!${NC}         ${YELLOW}│${NC}"
                    echo -e "  ${YELLOW}│${NC}                                                             ${YELLOW}│${NC}"
                    echo -e "  ${YELLOW}│${NC}  Make sure you have physical access to the device or know  ${YELLOW}│${NC}"
                    echo -e "  ${YELLOW}│${NC}  the new IP address before proceeding.                     ${YELLOW}│${NC}"
                    echo -e "  ${YELLOW}└─────────────────────────────────────────────────────────────┘${NC}"
                    echo ""

                    if ! confirm "Proceed with static IP configuration?" "n"; then
                        log_info "Static IP configuration cancelled"
                        return 0
                    fi

                    local iface
                    iface=$(detect_network_interface)
                    prompt_input "Enter static IP (CIDR format, e.g., 192.168.1.42/24)" "" STATIC_IP
                    prompt_input "Enter gateway IP" "" GATEWAY
                    ;;
                3|*)
                    log_info "Skipping network configuration"
                    return 0
                    ;;
            esac
        else
            return 0
        fi
    fi

    if [[ -z "${STATIC_IP:-}" ]]; then
        return 0
    fi

    # Validate CIDR format
    if ! validate_cidr "${STATIC_IP}"; then
        log_error "Invalid IP format: ${STATIC_IP} (use CIDR, e.g., 192.168.1.42/24)"
        return 1
    fi

    # Get gateway if not provided
    if [[ -z "${GATEWAY:-}" ]]; then
        # Try to auto-detect
        GATEWAY=$(ip route show default 2>/dev/null | awk '/default/ {print $3}' | head -1)
        if [[ -z "$GATEWAY" ]]; then
            log_error "Gateway required for static IP configuration"
            return 1
        fi
        log_info "Auto-detected gateway: $GATEWAY"
    fi

    print_section "Static IP Configuration"

    display_network_info

    local iface
    iface=$(detect_network_interface)

    echo ""
    echo -e "  ${YELLOW}WARNING: Network configuration changes may disconnect SSH.${NC}"
    echo -e "  ${INFO} New IP: ${STATIC_IP}"
    echo -e "  ${INFO} Gateway: ${GATEWAY}"
    echo ""

    if [[ "${NON_INTERACTIVE:-false}" != "true" ]]; then
        if ! confirm "Apply static IP configuration?" "n"; then
            log_info "Static IP configuration cancelled"
            return 0
        fi
    fi

    # Try dhcpcd first, then NetworkManager
    if [[ -f "${DHCPCD_CONF}" ]]; then
        configure_static_ip_dhcpcd "$iface" "${STATIC_IP}" "${GATEWAY}"
    elif command_exists nmcli; then
        configure_static_ip_nm "$iface" "${STATIC_IP}" "${GATEWAY}"
    else
        log_error "No supported network configuration method found"
        return 1
    fi

    log_success "Static IP configuration complete"
    return 0
}
