#!/bin/bash
# =============================================================================
# MDS Initialization Library: Systemd Services
# =============================================================================
# Version: 4.5.0
# Description: Systemd service installation, sudoers, polkit, and GPIO setup
# Author: MDS Team
# =============================================================================

# Prevent double-sourcing
[[ -n "${_MDS_SERVICES_LOADED:-}" ]] && return 0
_MDS_SERVICES_LOADED=1

# =============================================================================
# CONSTANTS
# =============================================================================

readonly SYSTEMD_DIR="/etc/systemd/system"
readonly SUDOERS_FILE="/etc/sudoers.d/mds-droneshow"
readonly POLKIT_FILE="/etc/polkit-1/rules.d/50-mds-droneshow.rules"

# Services in startup order
readonly SERVICE_ORDER=(
    "led_indicator.service"
    "wifi-manager.service"
    "git_sync_mds.service"
    "coordinator.service"
)

service_source_path() {
    case "${1:-}" in
        led_indicator.service)
            printf '%s\n' "tools/led_indicator/led_indicator.service"
            ;;
        wifi-manager.service)
            printf '%s\n' "tools/wifi-manager/wifi-manager.service"
            ;;
        git_sync_mds.service)
            printf '%s\n' "tools/git_sync_mds/git_sync_mds.service"
            ;;
        coordinator.service)
            printf '%s\n' "tools/coordinator.service"
            ;;
        *)
            return 1
            ;;
    esac
}

# =============================================================================
# SUDOERS CONFIGURATION
# =============================================================================

# Configure sudoers for droneshow user
configure_sudoers() {
    log_step "Configuring sudoers..."

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would configure: ${SUDOERS_FILE}${NC}"
        return 0
    fi

    # Create sudoers content
    local content
    content=$(cat << 'EOF'
# MDS Sudoers Configuration
# Generated by mds_node_init.sh
# Allows droneshow user to run specific commands without password

# Time synchronization
droneshow ALL=(ALL) NOPASSWD: /home/droneshow/mavsdk_drone_show/tools/sync_time.sh

# GPIO access for LED indicator
droneshow ALL=(ALL) NOPASSWD: /usr/bin/raspi-gpio

# System commands for service management
droneshow ALL=(ALL) NOPASSWD: /bin/systemctl status *
droneshow ALL=(ALL) NOPASSWD: /bin/systemctl restart coordinator
droneshow ALL=(ALL) NOPASSWD: /bin/systemctl restart wifi-manager

# Network diagnostics
droneshow ALL=(ALL) NOPASSWD: /sbin/ip addr
droneshow ALL=(ALL) NOPASSWD: /sbin/iwconfig

# Git operations (for sync service)
droneshow ALL=(ALL) NOPASSWD: /usr/bin/git
EOF
)

    # Backup existing
    if [[ -f "${SUDOERS_FILE}" ]]; then
        backup_file "${SUDOERS_FILE}"
    fi

    # Write new sudoers file
    echo "$content" > "${SUDOERS_FILE}"
    chmod 440 "${SUDOERS_FILE}"
    chown root:root "${SUDOERS_FILE}"

    # Verify sudoers syntax
    if visudo -c -f "${SUDOERS_FILE}" &>/dev/null; then
        log_success "Sudoers configured"
        return 0
    fi

    log_error "Invalid sudoers syntax - reverting"
    rm -f "${SUDOERS_FILE}"
    return 1
}

# =============================================================================
# POLKIT CONFIGURATION
# =============================================================================

# Configure polkit for reboot permissions
configure_polkit() {
    log_step "Configuring polkit rules..."

    # Check if polkit is installed
    if [[ ! -d /etc/polkit-1/rules.d ]]; then
        log_warn "Polkit not found, skipping polkit configuration"
        return 0
    fi

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would configure: ${POLKIT_FILE}${NC}"
        return 0
    fi

    # Create polkit rules content
    local content
    content=$(cat << 'EOF'
// MDS Polkit Rules
// Generated by mds_node_init.sh
// Allows droneshow user to reboot/poweroff without password

polkit.addRule(function(action, subject) {
    if ((action.id == "org.freedesktop.login1.reboot" ||
         action.id == "org.freedesktop.login1.reboot-multiple-sessions" ||
         action.id == "org.freedesktop.login1.power-off" ||
         action.id == "org.freedesktop.login1.power-off-multiple-sessions") &&
        subject.user == "droneshow") {
        return polkit.Result.YES;
    }
});
EOF
)

    # Backup existing
    if [[ -f "${POLKIT_FILE}" ]]; then
        backup_file "${POLKIT_FILE}"
    fi

    # Write polkit rules
    echo "$content" > "${POLKIT_FILE}"
    chmod 644 "${POLKIT_FILE}"
    chown root:root "${POLKIT_FILE}"

    log_success "Polkit rules configured"
    return 0
}

# =============================================================================
# GPIO CONFIGURATION
# =============================================================================

# Configure GPIO access for LED control
configure_gpio_access() {
    log_step "Configuring GPIO access..."

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would add ${MDS_USER} to gpio group${NC}"
        return 0
    fi

    # Check if gpio group exists
    if ! getent group gpio &>/dev/null; then
        log_info "GPIO group not found - creating"
        groupadd gpio 2>/dev/null || true
    fi

    # Add user to gpio group
    if usermod -aG gpio "${MDS_USER}" 2>/dev/null; then
        log_success "User added to gpio group"
    else
        log_warn "Failed to add user to gpio group (may already be member)"
    fi

    # Also add to dialout for serial access
    if getent group dialout &>/dev/null; then
        usermod -aG dialout "${MDS_USER}" 2>/dev/null || true
        log_info "User added to dialout group"
    fi

    # Add to video for display access
    if getent group video &>/dev/null; then
        usermod -aG video "${MDS_USER}" 2>/dev/null || true
        log_info "User added to video group"
    fi

    return 0
}

# =============================================================================
# SERVICE INSTALLATION
# =============================================================================

# Install a single service
install_service() {
    local service_name="$1"
    local source_path="$2"
    local full_source="${MDS_INSTALL_DIR}/${source_path}"
    local dest="${SYSTEMD_DIR}/${service_name}"

    log_step "Installing ${service_name}..."

    # Check if source exists
    if [[ ! -f "${full_source}" ]]; then
        log_warn "Service file not found: ${full_source}"
        return 1
    fi

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would install: ${full_source} -> ${dest}${NC}"
        return 0
    fi

    # Check if service file changed
    if [[ -f "${dest}" ]]; then
        local current_hash new_hash
        current_hash=$(md5sum "${dest}" 2>/dev/null | awk '{print $1}')
        new_hash=$(md5sum "${full_source}" 2>/dev/null | awk '{print $1}')

        if [[ "$current_hash" == "$new_hash" ]]; then
            log_info "${service_name} unchanged"
            return 0
        fi

        backup_file "${dest}"
    fi

    # Copy service file
    cp "${full_source}" "${dest}"
    chmod 644 "${dest}"
    chown root:root "${dest}"

    log_success "${service_name} installed"
    return 0
}

# Enable and start a service
enable_service() {
    local service_name="$1"

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would enable: ${service_name}${NC}"
        return 0
    fi

    # Enable service
    if systemctl enable "${service_name}" 2>/dev/null; then
        log_debug "Enabled: ${service_name}"
    else
        log_warn "Failed to enable: ${service_name}"
        return 1
    fi

    return 0
}

# Start a service
start_service() {
    local service_name="$1"

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would start: ${service_name}${NC}"
        return 0
    fi

    # Don't start services that run at boot only
    case "$service_name" in
        led_indicator.service)
            log_info "${service_name} is boot-only, not starting"
            return 0
            ;;
    esac

    if systemctl start "${service_name}" 2>/dev/null; then
        log_debug "Started: ${service_name}"
    else
        log_warn "Failed to start: ${service_name}"
        return 1
    fi

    return 0
}

# Install all MDS services
install_all_services() {
    log_step "Installing all MDS services..."

    local failed=0

    for service_name in "${SERVICE_ORDER[@]}"; do
        local source_path=""
        source_path=$(service_source_path "$service_name") || source_path=""

        if [[ -z "$source_path" ]]; then
            log_warn "Unknown service: ${service_name}"
            continue
        fi

        if ! install_service "$service_name" "$source_path"; then
            ((failed++))
        fi
    done

    if [[ $failed -gt 0 ]]; then
        log_warn "$failed service(s) failed to install"
    fi

    return 0
}

# Reload systemd daemon
reload_systemd() {
    log_step "Reloading systemd daemon..."

    if is_dry_run; then
        echo -e "  ${DIM}[DRY-RUN] Would run: systemctl daemon-reload${NC}"
        return 0
    fi

    systemctl daemon-reload
    log_success "Systemd daemon reloaded"
    return 0
}

# Enable all MDS services
enable_all_services() {
    log_step "Enabling MDS services..."

    local failed=0

    for service_name in "${SERVICE_ORDER[@]}"; do
        if ! enable_service "$service_name"; then
            ((failed++))
        fi
    done

    if [[ $failed -gt 0 ]]; then
        log_warn "$failed service(s) failed to enable"
    fi

    return 0
}

# =============================================================================
# VERIFICATION
# =============================================================================

# Verify service status
verify_services() {
    log_step "Verifying services..."

    echo ""
    printf "  ${BOLD}%-30s %-12s %-12s${NC}\n" "SERVICE" "ENABLED" "STATUS"
    echo -e "  ${DIM}$(printf '%.0s─' {1..54})${NC}"

    for service_name in "${SERVICE_ORDER[@]}"; do
        local enabled="no"
        local status="inactive"

        if service_is_enabled "$service_name"; then
            enabled="${GREEN}yes${NC}"
        else
            enabled="${YELLOW}no${NC}"
        fi

        if service_is_active "$service_name"; then
            status="${GREEN}active${NC}"
        else
            status="${DIM}inactive${NC}"
        fi

        printf "  %-30s %-22b %-22b\n" "$service_name" "$enabled" "$status"
    done

    echo ""
    return 0
}

# =============================================================================
# MAIN SERVICES RUNNER
# =============================================================================

run_services_phase() {
    print_phase_header "9" "Services Installation"

    # Check skip flag
    if [[ "${SKIP_SERVICES:-false}" == "true" ]]; then
        log_info "Skipping services installation (--skip-services)"
        return 0
    fi

    # Check if repository exists
    if [[ ! -d "${MDS_INSTALL_DIR}" ]]; then
        log_error "Repository not found. Run repository phase first."
        return 1
    fi

    print_section "System Permissions"

    # Configure sudoers
    configure_sudoers || log_warn "Sudoers configuration failed"

    # Configure polkit
    configure_polkit || log_warn "Polkit configuration failed"

    # Configure GPIO access
    configure_gpio_access || log_warn "GPIO configuration failed"

    print_section "Service Installation"

    set_led_state "SERVICES_UPDATING"

    # Install all services
    install_all_services

    # Reload systemd
    reload_systemd || return 1

    # Enable services
    enable_all_services

    print_section "Verification"

    verify_services

    log_success "Services installation complete"
    return 0
}
