/**
 * Auto-generated version information for MAVSDK Drone Show
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated by tools/version_sync.py
 *
 * To update the version:
 * 1. Edit the VERSION file in project root
 * 2. Run: python tools/version_sync.py
 * 3. Rebuild the frontend: npm run build
 */

export const VERSION = '3.6';
export const GIT_COMMIT = 'b4afd706';
export const GIT_BRANCH = 'main-candidate';
export const VERSION_DISPLAY = `v${VERSION} (${GIT_COMMIT})`;

export default {
  VERSION,
  GIT_COMMIT,
  GIT_BRANCH,
  VERSION_DISPLAY
};
