/**
 * Auto-generated version information for MAVSDK Drone Show
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated by tools/version_sync.py
 *
 * To update the version:
 * 1. Edit the VERSION file in project root
 * 2. Run: python tools/version_sync.py
 * 3. Rebuild the frontend: npm run build
 */

const VERSION = '3.7';
const GIT_COMMIT = '439b04c7';
const GIT_BRANCH = 'main-candidate';
const VERSION_DISPLAY = `v${VERSION} (${GIT_COMMIT})`;

export { VERSION, GIT_COMMIT, GIT_BRANCH, VERSION_DISPLAY };

export default {
  VERSION,
  GIT_COMMIT,
  GIT_BRANCH,
  VERSION_DISPLAY
};
