"""Shared .env-style file parsing and atomic update helpers."""

from __future__ import annotations

import os
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class EnvFileUpdateResult:
    """Result of a managed env-file update."""

    path: Path
    changed_keys: tuple[str, ...]
    existed_before: bool

    @property
    def changed(self) -> bool:
        return bool(self.changed_keys)


def parse_env_assignment_line(raw_line: str) -> tuple[str, str] | None:
    """Parse one KEY=value line from an env file.

    This parser intentionally supports the simple assignment format used by
    MDS-managed env files. It ignores comments, blank lines, and shell syntax
    that is unsafe to round-trip through operator APIs.
    """
    line = raw_line.strip()
    if not line or line.startswith("#") or "=" not in line:
        return None
    key, value = line.split("=", 1)
    key = key.strip()
    if not key:
        return None
    return key, value.strip().strip('"').strip("'")


def read_env_assignments(path: str | Path) -> dict[str, str]:
    values: dict[str, str] = {}
    env_path = Path(path)
    if not env_path.is_file():
        return values

    try:
        with env_path.open(encoding="utf-8") as handle:
            for raw_line in handle:
                parsed = parse_env_assignment_line(raw_line)
                if parsed is None:
                    continue
                key, value = parsed
                values[key] = value
    except OSError:
        return {}

    return values


def format_env_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def persist_env_updates(path: str | Path, updates: dict[str, Any], *, file_mode: int = 0o644) -> EnvFileUpdateResult:
    """Persist env updates atomically while preserving unrelated lines."""
    env_path = Path(path)
    env_path.parent.mkdir(parents=True, exist_ok=True)

    existed_before = env_path.exists()
    if existed_before:
        original_lines = env_path.read_text(encoding="utf-8").splitlines(keepends=True)
    else:
        timestamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        original_lines = [
            "# MDS Environment Configuration\n",
            f"# Generated by MDS on {timestamp}\n\n",
        ]

    changed_keys: list[str] = []
    remaining_keys = {key: format_env_value(value) for key, value in updates.items()}
    rendered_lines: list[str] = []

    for raw_line in original_lines:
        line = raw_line.rstrip("\n")
        stripped = line.strip()

        if stripped and not stripped.startswith("#") and "=" in line:
            key, _, current_value = line.partition("=")
            env_key = key.strip()
            if env_key in remaining_keys:
                desired_value = remaining_keys.pop(env_key)
                normalized_current = current_value.strip().strip('"').strip("'")
                if normalized_current != desired_value:
                    changed_keys.append(env_key)
                    rendered_lines.append(f"{env_key}={desired_value}\n")
                else:
                    rendered_lines.append(raw_line if raw_line.endswith("\n") else f"{raw_line}\n")
                continue

        rendered_lines.append(raw_line if raw_line.endswith("\n") else f"{raw_line}\n")

    if remaining_keys:
        if rendered_lines and rendered_lines[-1].strip():
            rendered_lines.append("\n")
        for env_key, desired_value in remaining_keys.items():
            changed_keys.append(env_key)
            rendered_lines.append(f"{env_key}={desired_value}\n")

    if not changed_keys:
        return EnvFileUpdateResult(path=env_path, changed_keys=(), existed_before=existed_before)

    fd, tmp_name = tempfile.mkstemp(prefix=f".{env_path.name}.", dir=str(env_path.parent))
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write("".join(rendered_lines))
        if existed_before:
            try:
                os.chmod(tmp_path, env_path.stat().st_mode & 0o777)
            except OSError:
                os.chmod(tmp_path, file_mode)
        else:
            os.chmod(tmp_path, file_mode)
        os.replace(tmp_path, env_path)
    finally:
        if tmp_path.exists():
            try:
                tmp_path.unlink()
            except OSError:
                pass

    return EnvFileUpdateResult(path=env_path, changed_keys=tuple(changed_keys), existed_before=existed_before)
