#!/usr/bin/env python3
"""Generate the MDS env registry markdown reference."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_PATH = REPO_ROOT / "docs" / "reference" / "mds-environment-registry.generated.md"

sys.path.insert(0, str(REPO_ROOT))

from src.settings.env_registry import EnvRegistry, EnvRegistryEntry, load_env_registry, redact_value  # noqa: E402


def _escape_cell(value: Any) -> str:
    text = "" if value is None else str(value)
    text = text.replace("\n", " ").replace("|", "\\|").strip()
    return text or "-"


def _code_cell(value: Any) -> str:
    text = _escape_cell(value)
    if text == "-":
        return text
    return f"`{text}`"


def _docs_link(entry: EnvRegistryEntry) -> str:
    docs_path = entry.docs.strip()
    if not docs_path:
        return "-"
    target = Path(docs_path)
    if docs_path.startswith("docs/"):
        target = Path("..") / Path(docs_path).relative_to("docs")
    return f"[guide]({target.as_posix()})"


def _entry_anchor(entry: EnvRegistryEntry) -> str:
    return "env-" + entry.name.lower().replace("_", "-")


def _entry_detail_lines(entry: EnvRegistryEntry) -> list[str]:
    default_value = redact_value(entry, entry.default)
    lines = [
        f'<a id="{_entry_anchor(entry)}"></a>',
        "",
        f"### `{entry.name}`",
        "",
        f"- Title: {_escape_cell(entry.title)}",
        f"- Scope: `{_escape_cell(entry.scope)}`",
        f"- Domain: `{_escape_cell(entry.domain)}`",
        f"- Type: `{_escape_cell(entry.value_type)}`",
        f"- Default: `{_escape_cell(default_value)}`",
        f"- Editable: {'yes' if entry.editable else 'no'}",
        f"- Restart: `{_escape_cell(entry.restart_required)}`",
        f"- Source of truth: `{_escape_cell(entry.source_of_truth)}`",
        f"- Apply action: `{_escape_cell(entry.apply_action)}`",
        f"- Docs: {_docs_link(entry)}",
    ]
    if entry.allowed_values:
        lines.append(f"- Allowed values: `{_escape_cell(', '.join(map(str, entry.allowed_values)))}`")
    if entry.notes:
        lines.append(f"- Notes: {_escape_cell(entry.notes)}")
    if entry.replacement:
        lines.append(f"- Replacement: `{_escape_cell(entry.replacement)}`")
    lines.append("")
    return lines


def build_env_reference_markdown(registry: EnvRegistry | None = None) -> str:
    registry = registry or load_env_registry()
    entries = registry.list_entries(include_hidden=True, include_deprecated=True)
    lines = [
        "# Generated MDS Environment Registry",
        "",
        "<!-- Generated by tools/generate_mds_env_reference.py; do not edit manually. -->",
        "",
        f"Registry version: `{registry.version}`",
        f"Registry hash: `{registry.content_hash}`",
        "",
        "| Key | Scope | Domain | Type | Default | Editable | Restart | Source | Docs |",
        "|---|---|---|---|---|---|---|---|---|",
    ]

    for entry in entries:
        default_value = redact_value(entry, entry.default)
        editable = "yes" if entry.editable else "no"
        lines.append(
            "| "
            + " | ".join(
                [
                    f"[`{_escape_cell(entry.name)}`](#{_entry_anchor(entry)})",
                    _escape_cell(entry.scope),
                    _escape_cell(entry.domain),
                    _escape_cell(entry.value_type),
                    _code_cell(default_value),
                    editable,
                    _escape_cell(entry.restart_required),
                    _escape_cell(entry.source_of_truth),
                    _docs_link(entry),
                ]
            )
            + " |"
        )

    lines.extend(["", "## Variable Details", ""])
    for entry in entries:
        lines.extend(_entry_detail_lines(entry))

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write the generated reference file")
    parser.add_argument("--check", action="store_true", help="fail if the generated reference file is stale")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="output markdown path",
    )
    args = parser.parse_args(argv)

    rendered = build_env_reference_markdown()
    if args.write:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
        print(f"wrote {args.output.relative_to(REPO_ROOT)}")
        return 0

    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except OSError:
            print(f"{args.output.relative_to(REPO_ROOT)} is missing", file=sys.stderr)
            return 1
        if current != rendered:
            print(f"{args.output.relative_to(REPO_ROOT)} is stale; run with --write", file=sys.stderr)
            return 1
        print(f"{args.output.relative_to(REPO_ROOT)} is current")
        return 0

    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
