#!/bin/bash
# =============================================================================
# MDS Deployment Profile Loader
# =============================================================================
# Loads the git-tracked deployment/defaults.env file and exports normalized
# default values for shell scripts. Host-local env files still override these
# defaults later in the runtime stack.
# =============================================================================

[[ -n "${_MDS_DEPLOYMENT_PROFILE_LOADED:-}" ]] && return 0 2>/dev/null || true
_MDS_DEPLOYMENT_PROFILE_LOADED=1

_MDS_DEPLOYMENT_PROFILE_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MDS_REPO_ROOT="${MDS_REPO_ROOT:-$(cd "${_MDS_DEPLOYMENT_PROFILE_SCRIPT_DIR}/.." && pwd)}"
DEFAULT_DEPLOYMENT_PROFILE_FILE="${MDS_REPO_ROOT}/deployment/defaults.env"
MDS_DEPLOYMENT_PROFILE_FILE="${MDS_DEPLOYMENT_PROFILE_FILE:-${DEFAULT_DEPLOYMENT_PROFILE_FILE}}"

if [[ -f "${MDS_DEPLOYMENT_PROFILE_FILE}" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "${MDS_DEPLOYMENT_PROFILE_FILE}"
    set +a
fi

MDS_DEFAULT_PROFILE_ID="${MDS_DEFAULT_PROFILE_ID:-official-default}"
MDS_DEFAULT_REPO_SLUG="${MDS_DEFAULT_REPO_SLUG:-alireza787b/mavsdk_drone_show}"
MDS_DEFAULT_REPO_URL_HTTPS="${MDS_DEFAULT_REPO_URL_HTTPS:-https://github.com/${MDS_DEFAULT_REPO_SLUG}.git}"
MDS_DEFAULT_REPO_URL_SSH="${MDS_DEFAULT_REPO_URL_SSH:-git@github.com:${MDS_DEFAULT_REPO_SLUG}.git}"
MDS_DEFAULT_BRANCH="${MDS_DEFAULT_BRANCH:-main-candidate}"
MDS_DEFAULT_REAL_GCS_IP="${MDS_DEFAULT_REAL_GCS_IP:-100.96.32.75}"
MDS_DEFAULT_SITL_GCS_IP="${MDS_DEFAULT_SITL_GCS_IP:-172.18.0.1}"
MDS_DEFAULT_GCS_API_PORT="${MDS_DEFAULT_GCS_API_PORT:-5000}"
MDS_DEFAULT_CONNECTIVITY_BACKEND="${MDS_DEFAULT_CONNECTIVITY_BACKEND:-none}"
MDS_DEFAULT_SMART_WIFI_MANAGER_REPO_SLUG="${MDS_DEFAULT_SMART_WIFI_MANAGER_REPO_SLUG:-alireza787b/smart-wifi-manager}"
MDS_DEFAULT_SMART_WIFI_MANAGER_REPO_URL_HTTPS="${MDS_DEFAULT_SMART_WIFI_MANAGER_REPO_URL_HTTPS:-https://github.com/${MDS_DEFAULT_SMART_WIFI_MANAGER_REPO_SLUG}.git}"
MDS_DEFAULT_SMART_WIFI_MANAGER_REF="${MDS_DEFAULT_SMART_WIFI_MANAGER_REF:-v2.1.0}"
MDS_DEFAULT_SMART_WIFI_MANAGER_MODE="${MDS_DEFAULT_SMART_WIFI_MANAGER_MODE:-observe}"
MDS_DEFAULT_SMART_WIFI_MANAGER_IMPORT_MODE="${MDS_DEFAULT_SMART_WIFI_MANAGER_IMPORT_MODE:-replace}"
MDS_DEFAULT_SMART_WIFI_MANAGER_INSTALL_DIR="${MDS_DEFAULT_SMART_WIFI_MANAGER_INSTALL_DIR:-/opt/smart-wifi-manager}"
MDS_DEFAULT_SMART_WIFI_MANAGER_DASHBOARD_LISTEN="${MDS_DEFAULT_SMART_WIFI_MANAGER_DASHBOARD_LISTEN:-127.0.0.1:9080}"
MDS_DEFAULT_SMART_WIFI_MANAGER_PROFILE_PATH="${MDS_DEFAULT_SMART_WIFI_MANAGER_PROFILE_PATH:-deployment/connectivity/smart-wifi-manager/profile.json}"
MDS_DEFAULT_MAVLINK_MANAGEMENT_MODE="${MDS_DEFAULT_MAVLINK_MANAGEMENT_MODE:-managed}"
MDS_DEFAULT_MAVLINK_ANYWHERE_REPO_SLUG="${MDS_DEFAULT_MAVLINK_ANYWHERE_REPO_SLUG:-alireza787b/mavlink-anywhere}"
MDS_DEFAULT_MAVLINK_ANYWHERE_REPO_URL_HTTPS="${MDS_DEFAULT_MAVLINK_ANYWHERE_REPO_URL_HTTPS:-https://github.com/${MDS_DEFAULT_MAVLINK_ANYWHERE_REPO_SLUG}.git}"
MDS_DEFAULT_MAVLINK_ANYWHERE_REF="${MDS_DEFAULT_MAVLINK_ANYWHERE_REF:-v3.0.7}"
MDS_DEFAULT_MAVLINK_ANYWHERE_INSTALL_DIR="${MDS_DEFAULT_MAVLINK_ANYWHERE_INSTALL_DIR:-/opt/mavlink-anywhere}"
MDS_DEFAULT_MAVLINK_ANYWHERE_DASHBOARD_LISTEN="${MDS_DEFAULT_MAVLINK_ANYWHERE_DASHBOARD_LISTEN:-127.0.0.1:9070}"
MDS_DEFAULT_MAVLINK_ANYWHERE_SKIP_DASHBOARD="${MDS_DEFAULT_MAVLINK_ANYWHERE_SKIP_DASHBOARD:-false}"

if [[ "${MDS_DEFAULT_REPO_SLUG}" == */* ]]; then
    MDS_DEFAULT_REPO_OWNER="${MDS_DEFAULT_REPO_SLUG%%/*}"
else
    MDS_DEFAULT_REPO_OWNER="${MDS_DEFAULT_REPO_SLUG}"
fi

export MDS_REPO_ROOT
export MDS_DEPLOYMENT_PROFILE_FILE
export MDS_DEFAULT_PROFILE_ID
export MDS_DEFAULT_REPO_SLUG
export MDS_DEFAULT_REPO_URL_HTTPS
export MDS_DEFAULT_REPO_URL_SSH
export MDS_DEFAULT_REPO_OWNER
export MDS_DEFAULT_BRANCH
export MDS_DEFAULT_REAL_GCS_IP
export MDS_DEFAULT_SITL_GCS_IP
export MDS_DEFAULT_GCS_API_PORT
export MDS_DEFAULT_CONNECTIVITY_BACKEND
export MDS_DEFAULT_SMART_WIFI_MANAGER_REPO_SLUG
export MDS_DEFAULT_SMART_WIFI_MANAGER_REPO_URL_HTTPS
export MDS_DEFAULT_SMART_WIFI_MANAGER_REF
export MDS_DEFAULT_SMART_WIFI_MANAGER_MODE
export MDS_DEFAULT_SMART_WIFI_MANAGER_IMPORT_MODE
export MDS_DEFAULT_SMART_WIFI_MANAGER_INSTALL_DIR
export MDS_DEFAULT_SMART_WIFI_MANAGER_DASHBOARD_LISTEN
export MDS_DEFAULT_SMART_WIFI_MANAGER_PROFILE_PATH
export MDS_DEFAULT_MAVLINK_MANAGEMENT_MODE
export MDS_DEFAULT_MAVLINK_ANYWHERE_REPO_SLUG
export MDS_DEFAULT_MAVLINK_ANYWHERE_REPO_URL_HTTPS
export MDS_DEFAULT_MAVLINK_ANYWHERE_REF
export MDS_DEFAULT_MAVLINK_ANYWHERE_INSTALL_DIR
export MDS_DEFAULT_MAVLINK_ANYWHERE_DASHBOARD_LISTEN
export MDS_DEFAULT_MAVLINK_ANYWHERE_SKIP_DASHBOARD
