#!/usr/bin/env python3
"""
Version Synchronization Script for MAVSDK Drone Show

This script reads the VERSION file and synchronizes the version number across:
- Python source code (src/__init__.py)
- Frontend package.json
- Frontend version.js (with git commit hash)

Usage:
    python tools/version_sync.py [--validate-only]

Options:
    --validate-only    Only validate version format without making changes
"""

import os
import sys
import re
import json
import subprocess
from pathlib import Path

# Project root directory
PROJECT_ROOT = Path(__file__).parent.parent.absolute()
VERSION_FILE = PROJECT_ROOT / "VERSION"

# Target files
PYTHON_INIT = PROJECT_ROOT / "src" / "__init__.py"
FRONTEND_PACKAGE_JSON = PROJECT_ROOT / "app" / "dashboard" / "drone-dashboard" / "package.json"
FRONTEND_VERSION_JS = PROJECT_ROOT / "app" / "dashboard" / "drone-dashboard" / "src" / "version.js"


def get_git_commit_hash():
    """Get short git commit hash"""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError:
        return "unknown"


def get_git_branch():
    """Get current git branch name"""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError:
        return "unknown"


def read_version():
    """Read version from VERSION file"""
    if not VERSION_FILE.exists():
        print(f"❌ ERROR: VERSION file not found at {VERSION_FILE}")
        sys.exit(1)

    version = VERSION_FILE.read_text().strip()

    # Validate format: X.Y (simple two-part versioning)
    if not re.match(r'^\d+\.\d+$', version):
        print(f"❌ ERROR: Invalid version format '{version}'")
        print("   Expected format: X.Y (e.g., 3.6, 4.0)")
        sys.exit(1)

    return version


def update_python_init(version):
    """Update src/__init__.py with version"""
    print(f"📝 Updating {PYTHON_INIT.relative_to(PROJECT_ROOT)}...")

    # Create file if it doesn't exist
    if not PYTHON_INIT.exists():
        PYTHON_INIT.parent.mkdir(parents=True, exist_ok=True)
        content = f'"""MAVSDK Drone Show - Python Source"""\n\n__version__ = "{version}"\n'
        PYTHON_INIT.write_text(content)
        print(f"   ✅ Created with version {version}")
        return

    # Read existing file
    content = PYTHON_INIT.read_text()

    # Replace or add __version__
    version_pattern = r'__version__\s*=\s*["\'][\d.]+["\']'
    new_version_line = f'__version__ = "{version}"'

    if re.search(version_pattern, content):
        new_content = re.sub(version_pattern, new_version_line, content)
    else:
        # Add to end of file
        if content and not content.endswith('\n'):
            content += '\n'
        new_content = content + f'\n{new_version_line}\n'

    PYTHON_INIT.write_text(new_content)
    print(f"   ✅ Updated to version {version}")


def update_package_json(version):
    """Update frontend package.json with version"""
    print(f"📝 Updating {FRONTEND_PACKAGE_JSON.relative_to(PROJECT_ROOT)}...")

    if not FRONTEND_PACKAGE_JSON.exists():
        print(f"   ❌ ERROR: package.json not found")
        sys.exit(1)

    # Read and parse JSON
    with open(FRONTEND_PACKAGE_JSON, 'r') as f:
        package_data = json.load(f)

    # Update version
    package_data['version'] = version

    # Write back with pretty formatting
    with open(FRONTEND_PACKAGE_JSON, 'w') as f:
        json.dump(package_data, f, indent=2)
        f.write('\n')  # Add trailing newline

    print(f"   ✅ Updated to version {version}")


def generate_version_js(version):
    """Generate frontend version.js with version and git hash"""
    print(f"📝 Generating {FRONTEND_VERSION_JS.relative_to(PROJECT_ROOT)}...")

    # Ensure directory exists
    FRONTEND_VERSION_JS.parent.mkdir(parents=True, exist_ok=True)

    git_hash = get_git_commit_hash()
    git_branch = get_git_branch()

    content = f'''/**
 * Auto-generated version information for MAVSDK Drone Show
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated by tools/version_sync.py
 *
 * To update the version:
 * 1. Edit the VERSION file in project root
 * 2. Run: python tools/version_sync.py
 * 3. Rebuild the frontend: npm run build
 */

const VERSION = '{version}';
const GIT_COMMIT = '{git_hash}';
const GIT_BRANCH = '{git_branch}';
const VERSION_DISPLAY = `v${{VERSION}} (${{GIT_COMMIT}})`;

export {{ VERSION, GIT_COMMIT, GIT_BRANCH, VERSION_DISPLAY }};

export default {{
  VERSION,
  GIT_COMMIT,
  GIT_BRANCH,
  VERSION_DISPLAY
}};
'''

    FRONTEND_VERSION_JS.write_text(content)
    print(f"   ✅ Generated: v{version} ({git_hash}) on {git_branch}")


def validate_only(version):
    """Validate version format and show what would be updated"""
    print(f"✅ Version format valid: {version}")
    print(f"\nWould update:")
    print(f"  - {PYTHON_INIT.relative_to(PROJECT_ROOT)}")
    print(f"  - {FRONTEND_PACKAGE_JSON.relative_to(PROJECT_ROOT)}")
    print(f"  - {FRONTEND_VERSION_JS.relative_to(PROJECT_ROOT)}")
    print(f"\nRun without --validate-only to apply changes")


def main():
    """Main entry point"""
    print("=" * 60)
    print("MAVSDK Drone Show - Version Synchronization")
    print("=" * 60)
    print()

    # Check for validate-only flag
    validate_mode = '--validate-only' in sys.argv

    # Read version
    version = read_version()
    print(f"📌 Current version: {version}")
    print()

    if validate_mode:
        validate_only(version)
        return

    # Update all files
    update_python_init(version)
    update_package_json(version)
    generate_version_js(version)

    print()
    print("=" * 60)
    print("✅ Version synchronization complete!")
    print("=" * 60)
    print()
    print("Next steps:")
    print("  1. Review the changes")
    print("  2. Rebuild frontend: cd app/dashboard/drone-dashboard && npm run build")
    print("  3. Commit changes: git add -A && git commit -m 'chore: bump version to " + version + "'")
    print()


if __name__ == "__main__":
    main()
