"""Shared canonical drone API route constants for runtime and tooling callers."""

DRONE_STATE_ROUTE = "/api/v1/drone/state"
DRONE_LIVE_ARMABILITY_ROUTE = "/api/v1/preflight/armability"
DRONE_COMMANDS_ROUTE = "/api/v1/drone/commands"
DRONE_NAVIGATION_HOME_ROUTE = "/api/v1/navigation/home"
DRONE_NAVIGATION_GLOBAL_ORIGIN_ROUTE = "/api/v1/navigation/global-origin"
DRONE_POSITION_DEVIATION_ROUTE = "/api/v1/navigation/position-deviation"
DRONE_GIT_STATUS_ROUTE = "/api/v1/git/status"
DRONE_SYSTEM_HEALTH_ROUTE = "/api/v1/system/health"
DRONE_NETWORK_STATUS_ROUTE = "/api/v1/network/status"
DRONE_SWARM_CONFIG_ROUTE = "/api/v1/swarm/config"
DRONE_LOCAL_POSITION_ROUTE = "/api/v1/telemetry/local-position"
DRONE_WS_STATE_ROUTE = "/ws/drone-state"
