"""Shared canonical drone API route constants for runtime and tooling callers."""

DRONE_STATE_ROUTE = "/api/v1/drone/state"
DRONE_LIVE_ARMABILITY_ROUTE = "/api/v1/preflight/armability"
DRONE_COMMANDS_ROUTE = "/api/v1/drone/commands"
DRONE_NAVIGATION_HOME_ROUTE = "/api/v1/navigation/home"
DRONE_NAVIGATION_GLOBAL_ORIGIN_ROUTE = "/api/v1/navigation/global-origin"
DRONE_POSITION_DEVIATION_ROUTE = "/api/v1/navigation/position-deviation"
DRONE_GIT_STATUS_ROUTE = "/api/v1/git/status"
DRONE_SYSTEM_HEALTH_ROUTE = "/api/v1/system/health"
DRONE_NETWORK_STATUS_ROUTE = "/api/v1/network/status"
DRONE_SWARM_CONFIG_ROUTE = "/api/v1/swarm/config"
DRONE_LOCAL_POSITION_ROUTE = "/api/v1/telemetry/local-position"
DRONE_PX4_PARAMS_POLICY_ROUTE = "/api/v1/px4-params/policy"
DRONE_PX4_PARAMS_SNAPSHOT_REFRESH_ROUTE = "/api/v1/px4-params/snapshots/refresh"
DRONE_PX4_PARAMS_SNAPSHOT_CURRENT_ROUTE = "/api/v1/px4-params/snapshots/current"
DRONE_PX4_PARAM_VALUE_ROUTE_TEMPLATE = "/api/v1/px4-params/values/{name}"
DRONE_PX4_PARAMS_PATCH_APPLY_ROUTE = "/api/v1/px4-params/patches/apply"
DRONE_WS_STATE_ROUTE = "/ws/drone-state"
