"""Shared canonical GCS route constants for runtime and tooling callers."""

GCS_COMMAND_REPORT_EXECUTION_START_ROUTE = "/api/v1/command-reports/execution-start"
GCS_COMMAND_REPORT_EXECUTION_RESULT_ROUTE = "/api/v1/command-reports/execution-result"
GCS_ORIGIN_BOOTSTRAP_ROUTE = "/api/v1/origin/bootstrap"
GCS_SHOW_IMPORT_ROUTE = "/api/v1/shows/skybrush/import"
GCS_SHOW_INFO_ROUTE = "/api/v1/shows/skybrush"
GCS_CUSTOM_SHOW_INFO_ROUTE = "/api/v1/shows/custom"
GCS_SWARM_TRAJECTORY_BASE_ROUTE = "/api/v1/swarm-trajectories"
GCS_SWARM_TRAJECTORY_LEADERS_ROUTE = f"{GCS_SWARM_TRAJECTORY_BASE_ROUTE}/leaders"
GCS_SWARM_TRAJECTORY_STATUS_ROUTE = f"{GCS_SWARM_TRAJECTORY_BASE_ROUTE}/status"
GCS_SWARM_TRAJECTORY_PROCESS_ROUTE = f"{GCS_SWARM_TRAJECTORY_BASE_ROUTE}/process"
